name: Docker Compose Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-the-application:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2
        with:
          version: latest

      - name: Pull Docker image
        run: |
          sudo docker pull rohankalamakar/e-commerce:latest

      - name: Deploy using Docker Compose
        working-directory: ./frontend
        run: docker run -d -p 3000:3000 --name ecommerce-final  rohankalamakar/e-commerce:latest