name: Docker Compose Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-the-application:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: docker-compose-install
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin
          sudo docker compose version


      - name: Pull Docker image
        run: |
          sudo docker pull rohankalamakar/e-commerce:latest

      - name: Deploy using Docker Compose
        working-directory: ./frontend
        run: |
          sudo docker compose down
          sudo docker compose pull
          sudo docker compose up -d

      - name: Check running containers
        working-directory: ./frontend
        run: |
          sudo docker compose ps