# GOAL IS TO CHECK LEAK
name: gitleak

on:
  workflow_dispatch:

jobs:
  leaks-find:
  runs-on: ubuntu-latest
  steps:
    - name: Code-checkout
      uses: actions/checkout@v4
    
    - name: gitleaks
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v6
          working-directory: ./frontend
          with:
            fetch-depth: 0
        - uses: gitleaks/gitleaks-action@v3
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
# f
