# Goal is to lint the code 

name: Linting

on:
  workflow_call:
    branches:
        - main
  pull_request:
    branches:
      - main


jobs:
  lint-the-code:
    runs-on: ubuntu-latest
    
    steps:
      - name: code-checkout
        uses: actions/checkout@v4

      - name: steup-the-node.js-env
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' 
          cache-dependency-path: frontend/package-lock.json

    
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
    
      - name: Run Linter
        working-directory: ./frontend
        run: npm run lint
