# Goal is to review the code usfig SAST
name: code-review-SAST

on:
  push:
    branches:
      - main
jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: code-checkout
        uses: actions/checkout@v4
      
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8.2.1
        env:
          SONAR_TOKEN: 5932d2e83da9225073ebe9f5aa3529d056674a65
          SONAR_HOST_URL: https://sonarcloud.io/

# pop

