# Goal is to check the docker image /container to sure any security threat

name: Trivy-check
on:
  push:
    branches:
      - main
  
jobs: 
  trivy-check:
    runs-on: ubuntu-latest

    steps:
      - name: code-checkout
        uses: actions/checkout@v4

      - name: Docker-setup
        run: |
          docker --version
          docker info

        
      - name: Build an image from Dockerfile
        run: docker build -t application/${{ vars.DOCKERHUB_USERNAME }} ./frontend
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'application/${{ vars.DOCKERHUB_USERNAME }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
